### ISSUE TITLE
Risk Analysis specific D3 graphs

### ISSUE THREAD

**Issue by peterhambly** [smallAreaHealthStatisticsUnit/rapidInquiryFacility#127]
These will replace the posterior probability J curve and the frequency count the FP defined D3 charts displaying the homogeneity data.

This will be based on the visible displays in the RIF 3.2, for point source exposures (minimum displayed dataset to include observed counts, expected counts, relative risk, trend test for each site, and adjusted by region with heterogeneity testing and meta-analysis function. The content and layout should be discussed with FP

* Covariate loss report. This will be added to study summary report (the (i) button in the data viewer. Study summary is currently broken:
  ![Covariate data loss RIF 3.2 popups](https://smallareahealthstatisticsunit.github.io/rapidInquiryFacility/plans/Covariate%20data%20loss%20RIF%203.2%20popups.png)
* RIF 3.2 risk analysis results [replacement for the frequency count]:
  ![RIF 3.2 risk analysis results](https://smallareahealthstatisticsunit.github.io/rapidInquiryFacility/plans/RIF%203.2%20risk%20analysis%20results.png)
* RIF 3.2 risk analysis graph [replacement for the posterior probability J curve]:
  ![RIF 3.2 risk analysis graph](https://smallareahealthstatisticsunit.github.io/rapidInquiryFacility/plans/RIF%203.2%20risk%20analysis%20graph.png);

Study summary error appears to be a porting fault and is trivial to fix (rif40 schema is missing):
```
11:19:09.860 [http-nio-8080-exec-6] ERROR org.sahsu.rif.generic.util.CommonLogger : [org.sahsu.rif.services.datastorage.common.SmoothedResultManager]:
SmoothedResultManager.getHealthCodesForProcessedStudy error
getMessage:          SQLServerException: Invalid object name 'rif40_inv_conditions'.
getRootCauseMessage: SQLServerException: Invalid object name 'rif40_inv_conditions'.
getThrowableCount:   1
getRootCauseStackTrace >>>
com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'rif40_inv_conditions'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:259)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1547)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:548)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:479)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7344)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2713)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:224)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:204)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:401)
	at org.sahsu.rif.services.datastorage.common.SmoothedResultManager.getHealthCodesForProcessedStudy(SmoothedResultManager.java:387)
	at org.sahsu.rif.services.datastorage.common.StudyRetrievalService.getHealthCodesForProcessedStudy(StudyRetrievalService.java:834)
	at org.sahsu.rif.services.rest.StudyResultRetrievalServiceResource.getHealthCodesForProcessedStudy(StudyResultRetrievalServiceResource.java:697)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`
```

Tasks:

* Modify front end to support new D3 graphs and the covariate loss report;
* Create a new REST middleware service *getHomegeneity* to return the rif40_homegeneity data for the study with parameters: username and studyID. I to 3 JSON records expected containing:
  * genders
  * homogeneity_dof
  * homogeneity_chi2
  * homogeneity_p
  * linearity_chi2
  * linearity_p
  * explt5;
* Fix study summary report;
* Create a new REST middleware service *getCovariateLossReport* to return the covariate loss report; this will *LEFT OUTER JOIN* the numerator and covariate tables, filter by the study and comparison areas respectively, and filter the covariates the max and min  ranges defined for the covariate to produce:
  * Study or Comparision areas (S or C);
  * Covariate name;
  * Number of areas at mapping (covariate table) geolevel;
  * Number of areas that join the numerator to the study or Comparision area for the study defined year and age sex group range;
  * Number of areas that join the covaite to the study or Comparision area for defined coviate max/min limits;
REST parameters: username and studyID, returns two x number of covariates records for a risk analysis study using covariates; otherwise an error;

**Comment by peterhambly** [comment]
This is now completed by pull #135 for issue #127 Risk Analysis specific D3 graphs. Issue #134 D3 graphs todo superceeds
