### ISSUE TITLE
Add support for risk analysis in map export

### ISSUE THREAD

**Issue by peterhambly** [smallAreaHealthStatisticsUnit/rapidInquiryFacility#61]
Add support for risk analysis in map export

```
Error: res.data.rif_job_submission.disease_mapping_study[whyDidYouDoItLikeThatKevin] is undefined
$scope.updateStudy/</<@http://localhost:8080/RIF40/dashboards/export/controllers/rifc-expt-export.js:446:61
e/<@http://localhost:8080/RIF40/libs/standalone/angular.min.js:131:20
$eval@http://localhost:8080/RIF40/libs/standalone/angular.min.js:145:343
$digest@http://localhost:8080/RIF40/libs/standalone/angular.min.js:142:412
$apply@http://localhost:8080/RIF40/libs/standalone/angular.min.js:146:111
l@http://localhost:8080/RIF40/libs/standalone/angular.min.js:97:320
J@http://localhost:8080/RIF40/libs/standalone/angular.min.js:102:34
gg/</t.onload@http://localhost:8080/RIF40/libs/standalone/angular.min.js:103:4
 angular.min.js:118:8
```

```
16:53:50.605 [http-nio-8080-exec-11] WARN  org.sahsu.rif.generic.util.RIFLogger : [org.sahsu.rif.services.graphics.RIFStyle]:
Error in RIFStyle() constructor
getMessage:          NullPointerException: 
getRootCauseMessage: NullPointerException: 
getThrowableCount:   1
getRootCauseStackTrace >>>
java.lang.NullPointerException
	at org.geotools.filter.function.QuantileFunction.calculate(QuantileFunction.java:71)
	at org.geotools.filter.function.QuantileFunction.evaluate(QuantileFunction.java:153)
	at org.sahsu.rif.services.graphics.RIFStyle.createPredefinedRifStyle(RIFStyle.java:306)
	at org.sahsu.rif.services.graphics.RIFStyle.<init>(RIFStyle.java:193)
	at org.sahsu.rif.services.graphics.RIFMapsParameters$RIFMapsParameter.getRIFStyle(RIFMapsParameters.java:167)
	at org.sahsu.rif.services.graphics.RIFMaps.writeResultsMaps(RIFMaps.java:237)
	at org.sahsu.rif.services.datastorage.common.RifGeospatialOutputs.writeGeospatialFiles(RifGeospatialOutputs.java:260)
	at org.sahsu.rif.services.datastorage.common.RifZipFile.createStudyExtract(RifZipFile.java:415)
	at org.sahsu.rif.services.datastorage.common.StudyExtractManager.createStudyExtract(StudyExtractManager.java:191)
	at org.sahsu.rif.services.datastorage.common.StudyExtract.create(StudyExtract.java:81)
	at org.sahsu.rif.services.datastorage.common.StudySubmissionService.createStudyExtract(StudySubmissionService.java:1331)
	at org.sahsu.rif.services.rest.WebService.createZipFile(WebService.java:1095)
	at org.sahsu.rif.services.rest.StudySubmissionServiceResource.createZipFile(StudySubmissionServiceResource.java:1177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

```
16:53:50.612 [http-nio-8080-exec-11] INFO  org.sahsu.rif.generic.util.RIFLogger : [org.sahsu.rif.services.datastorage.common.RifZipFile]:
Create ZIP file exception trace: c:\rifDemo\scratchSpace\peter_s447_1002_lung_cancer.err
16:53:50.618 [http-nio-8080-exec-11] ERROR org.sahsu.rif.generic.util.RIFLogger : [org.sahsu.rif.services.datastorage.common.StudyExtract]:
createStudyExtract
getMessage:          RIFServiceException: Unable to create extract for user "peter", zipfile "c:\rifDemo\scratchSpace\peter_s447_1002_lung_cancer.zip".
getRootCauseMessage: RIFServiceException: Unable to create extract for user "peter", zipfile "c:\rifDemo\scratchSpace\peter_s447_1002_lung_cancer.zip".
getThrowableCount:   1
getRootCauseStackTrace >>>
1 error(s). Error code is 'ZIPFILE_CREATE_FAILED'. Message list is: 'Unable to create extract for user "peter", zipfile "c:\rifDemo\scratchSpace\peter_s447_1002_lung_cancer.zip".'
	at org.sahsu.rif.services.datastorage.common.RifZipFile.createStudyExtract(RifZipFile.java:558)
	at org.sahsu.rif.services.datastorage.common.StudyExtractManager.createStudyExtract(StudyExtractManager.java:191)
	at org.sahsu.rif.services.datastorage.common.StudyExtract.create(StudyExtract.java:81)
	at org.sahsu.rif.services.datastorage.common.StudySubmissionService.createStudyExtract(StudySubmissionService.java:1331)
	at org.sahsu.rif.services.rest.WebService.createZipFile(WebService.java:1095)
	at org.sahsu.rif.services.rest.StudySubmissionServiceResource.createZipFile(StudySubmissionServiceResource.java:1177
```

**Comment by peterhambly** [comment]
Investigate and fix risk analysis export NPE crash: caused by smoothed_smr, posterior_probability fields with no data; pull #73
